config/routes.rb
Rails.application.routes.draw do
  get 'datajet/index'

  get 'splash/index'

  resources :diesels
  resources :msrecords

   root 'datajet#index'

end

app/models/msrecord.rb
class Msrecord < ActiveRecord::Base
  validates :reading_at, presence: true
  validates :received_stock, :actual_stock, :opening_meter, :testing_meter, presence: true, numericality: true
  validates :purchase_rate, :sale_rate, presence: true, numericality: true


  def prev_closing_meter previous_record
    return previous_record unless previous_record
    previous_record.closing_meter = self.opening_meter
    previous_record
  end

  def prev_actual_sale previous_record
    return previous_record unless previous_record
    previous_record.actual_sale = self.opening_meter - previous_record.opening_meter - previous_record.testing_meter
    previous_record
  end

  def prev_closing_stock previous_record
    return previous_record unless previous_record
    previous_record.closing_stock = previous_record.total_stock - previous_record.actual_sale
    previous_record
  end

  def current_total_stock previous_record
    previous_record.nil? ? self.total_stock = self.received_stock  : self.total_stock = previous_record.closing_stock + self.received_stock
  end

  def current_opening_stock previous_record
    previous_record.nil? ? self.opening_stock = 0 : self.opening_stock = previous_record.closing_stock
  end

  def next
    self.class.where("id > ?", id).first
  end

  def previous
    self.class.where("id < ?", id).last
  end

  def self.search(start_date, end_date)
    where("reading_at >= ? and reading_at <= ?", start_date, end_date)
  end

  def self.to_csv()
    column_names  = ["Date", "Opening Stock", "Received Stock", "Actual Stock", "Total Stock", "Closing Stock", "Opening Meter",
                     "Testing Meter", "Closing Meter", "Actual Sale", "Purchase Rate", "Sale Rate"]
    attributes    = %w{reading_at opening_stock received_stock actual_stock total_stock closing_stock opening_meter
                    testing_meter closing_meter actual_sale purchase_rate sale_rate}

    CSV.generate(headers: true) do |csv|
      csv << column_names
      all.each do |msrecord|
        #csv << msrecord.attributes.values_at(*attributes)
        csv << attributes.map{ |attr| msrecord.send(attr) }
      end
    end
  end
end

app/controllers/msrecords_controller.rb
class MsrecordsController < ApplicationController

  include ApplicationHelper

  around_filter :catch_not_found

  # index, show, new, edit, create, update and destroy

  http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

  def index
    if params[:start_date].blank? or params[:end_date].blank?
      @msrecords   = Msrecord.all
    else
      start_date = params[:start_date].to_date
      end_date   = params[:end_date].to_date
      @msrecords   = Msrecord.search(start_date, end_date)
    end

    respond_to do |format|
      format.html
      format.csv { send_data @msrecords.to_csv, filename: "msrecord-#{Time.now.strftime("%d-%m-%Y-%R")}.csv" }
      format.xlsx { render xlsx: 'excel', filename: "msrecord-#{Date.today}.xlsx" }
    end
  end

  def show
    @msrecord = Msrecord.find(params[:id])
  end

  def new
    @msrecord = Msrecord.new
  end

  def edit
    @msrecord = Msrecord.find(params[:id])
  end

  def create
    @msrecord = Msrecord.new(msrecord_params)

    @previous_record = Msrecord.last
    @previous_record = @msrecord.prev_closing_meter @previous_record
    @previous_record = @msrecord.prev_actual_sale @previous_record
    @previous_record = @msrecord.prev_closing_stock @previous_record

    @msrecord.current_total_stock @previous_record
    @msrecord.current_opening_stock @previous_record

    if @msrecord.save
      @previous_record.save unless @previous_record.nil?
      redirect_to @msrecord
    else
      render 'new'
    end
  end

  def update
    @msrecord = Msrecord.find(params[:id])

    @previous_record = @msrecord.previous
    @previous_record = @msrecord.prev_closing_meter @previous_record
    @previous_record = @msrecord.prev_actual_sale @previous_record
    @previous_record = @msrecord.prev_closing_stock @previous_record

    @msrecord.current_total_stock @previous_record
    @msrecord.current_opening_stock @previous_record

    if @msrecord.update(msrecord_params)
      @previous_record.save unless @previous_record.nil?
      redirect_to @msrecord
    else
      render 'edit'
    end
  end

  def destroy
    @msrecord = Msrecord.find(params[:id])
    @msrecord.destroy

    redirect_to msrecords_path
  end

  private
  def msrecord_params
    params.require(:msrecord).permit(:reading_at,
                                   :received_stock,
                                   :actual_stock,
                                   :opening_meter,
                                   :testing_meter,
                                   :purchase_rate,
                                   :sale_rate)
  end

  def catch_not_found
    yield
  rescue ActiveRecord::RecordNotFound
    redirect_to msrecords_path, :flash => { :error => "Record not found." }
  end
end

app/helpers/msrecords_helper.rb
module MsrecordsHelper
end

app/views/msrecords/_form.html.erb
<%= form_for(@msrecord, html: {class: 'form-horizontal'}) do |f| %>

  <% if @msrecord.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@msrecord.errors.count, "error") %> prohibited this record from being saved:
      </h2>
      <ul>
        <% @msrecord.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :date, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.date_select :reading_at, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :received_stock, class: 'col-sm-2 control-label' %>
    <div class="col-sm-2">
      <%= f.number_field :received_stock, class: 'form-control' , :'data-toggle' => 'popover', :'data-trigger' => 'hover', :'data-placement' => 'bottom', :'data-content' => 'Stock added today' %>
    </div>
    <%= f.label :actual_stock, class: 'col-sm-2 control-label' %>
    <div class="col-sm-2">
      <%= f.number_field :actual_stock, class: 'form-control', :'data-toggle' => 'popover', :'data-trigger' => 'hover', :'data-placement' => 'bottom', :'data-content' => 'Tank dip reading' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :opening_meter, class: 'col-sm-2 control-label' %>
    <div class="col-sm-2">
      <%= f.number_field :opening_meter, class: 'form-control' , :'data-toggle' => 'popover', :'data-trigger' => 'hover', :'data-placement' => 'bottom', :'data-content' => 'HSD machine meter reading' %>
    </div>
    <%= f.label :testing_meter, class: 'col-sm-2 control-label' %>
    <div class="col-sm-2">
      <%= f.number_field :testing_meter, class: 'form-control' , :'data-toggle' => 'popover', :'data-trigger' => 'hover', :'data-placement' => 'bottom', :'data-content' => 'HSD testing value' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :purchase_rate, class: 'col-sm-2 control-label' %>
    <div class="col-sm-2">
      <%= f.number_field :purchase_rate, class: 'form-control', step: 0.001, :'data-toggle' => 'popover', :'data-trigger' => 'hover', :'data-placement' => 'bottom', :'data-content' => 'Purchase rate for stock-in HSD' %>
    </div>
    <%= f.label :sale_rate, class: 'col-sm-2 control-label' %>
    <div class="col-sm-2">
      <%= f.number_field :sale_rate, class: 'form-control', step: 0.001, :'data-toggle' => 'popover', :'data-trigger' => 'hover', :'data-placement' => 'bottom', :'data-content' => 'Current sale rate for HSD' %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= button_tag "Add", class: "btn btn-success", :type => 'submit' do %>
        <i class="glyphicon glyphicon-ok"></i> Add
      <% end %>
      <%= button_tag "Clear", class: "btn btn-danger", :type => 'reset' do %>
        <i class="glyphicon glyphicon-remove"></i> Clear
      <% end %>
    </div>
  </div>
<% end %>

app/views/msrecords/_searchform.html.erb
<%= form_tag(msrecords_path, :method => "get", class: "navbar-form") do %>
  <div class="input-append">
    <%= date_field_tag :start_date, params[:start_date] %>
    <%= date_field_tag :end_date, params[:end_date] %>
    <button class="btn btn-primary" type="submit"><i class="glyphicon glyphicon-search"></i></button>
  </div>
<% end %>

app/views/msrecords/edit.html.erb
<div class="container">
  <h1>Editing petrol record</h1>

  <%= render 'form' %>

  <%= link_to msrecords_path, class: "btn btn-info btn-sm" do %>
    <i class="glyphicon glyphicon-arrow-left"></i> Back
  <% end %>
</div>

app/views/msrecords/index.html.erb
<%= render 'searchform' %>

<div class="container-fluid">
  <h1>Listing petrol records</h1>

  <p><%= link_to new_msrecord_path, class: "btn btn-primary btn-sm" do %>
    <i class="glyphicon glyphicon-plus"></i> New petrol record
  <% end %>
</p>

<table class="table table-hover table-condensed">
  <tr>
    <th>Date</th>
    <th>Opening Stock</th>
    <th>Received Stock</th>
    <th>Actual Stock</th>
    <th>Total Stock</th>
    <th>Closing Stock</th>
    <th>Opening Meter</th>
    <th>Testing Meter</th>
    <th>Closing Meter</th>
    <th>Actual Sale</th>
    <th>Purchase Rate</th>
    <th>Sale Rate</th>
    <th colspan="13"></th>
  </tr>

  <% @msrecords.each do |msrecord| %>
    <tr>
      <td><%= msrecord.reading_at %></td>
      <td><%= msrecord.opening_stock %></td>
      <td><%= msrecord.received_stock %></td>
      <td><%= msrecord.actual_stock %></td>
      <td><%= msrecord.total_stock %></td>
      <td><%= msrecord.closing_stock %></td>
      <td><%= msrecord.opening_meter %></td>
      <td><%= msrecord.testing_meter %></td>
      <td><%= msrecord.closing_meter %></td>
      <td><%= msrecord.actual_sale %></td>
      <td><%= msrecord.purchase_rate %></td>
      <td><%= msrecord.sale_rate %></td>
      <td>
        <%= link_to msrecord_path(msrecord), class: "btn btn-primary btn-xs" do %>
          <i class="glyphicon glyphicon-th-list"></i> Show
        <% end %>
        <%= link_to edit_msrecord_path(msrecord), class: "btn btn-warning btn-xs" do %>
          <i class="glyphicon glyphicon-pencil"></i> Edit
        <% end %>
        <%= link_to msrecord_path(msrecord), class: "btn btn-danger btn-xs",
          method: :delete,
          data: { confirm: 'Are you sure?' } do %>
          <i class="glyphicon glyphicon-remove"></i> Delete
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<p>
  <strong>Download as:</strong>
  <%= link_to msrecords_path(params.merge(format: "csv")), class: "btn btn-info btn-sm" do %>
    <i class="glyphicon glyphicon-save"></i> CSV
  <% end %>
  <%= link_to msrecords_path(params.merge(format: "xlsx")) , class: "btn btn-info btn-sm" do %>
    <i class="glyphicon glyphicon-save"></i> Excel
  <% end %>
</p>
</div>

app/views/msrecords/new.html.erb
<div class="container">
  <h1>New petrol record</h1>

  <%= render 'form' %>

  <%= link_to msrecords_path, class: "btn btn-info btn-sm" do %>
    <i class="glyphicon glyphicon-arrow-left"></i> Back
  <% end %>
</div>

app/views/msrecords/show.html.erb
<div class="container">
  <h3>Petrol Record for:
    <%= @msrecord.reading_at %>
  </h3>
  <div class="table-responsive">
    <table class="table table-hover table-condensed">
      <thead>
        <tr>
          <th>Date</th>
          <th>Opening Stock</th>
          <th>Received Stock</th>
          <th>Actual Stock</th>
          <th>Total Stock</th>
          <th>Closing Stock</th>
          <th>Opening Meter</th>
          <th>Testing Meter</th>
          <th>Closing Meter</th>
          <th>Actual Sale</th>
          <th>Purchase Rate</th>
          <th>Sale Rate</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @msrecord.reading_at %></td>
          <td><%= @msrecord.opening_stock %></td>
          <td><%= @msrecord.received_stock %></td>
          <td><%= @msrecord.actual_stock %></td>
          <td><%= @msrecord.total_stock %></td>
          <td><%= @msrecord.closing_stock %></td>
          <td><%= @msrecord.opening_meter %></td>
          <td><%= @msrecord.testing_meter %></td>
          <td><%= @msrecord.closing_meter %></td>
          <td><%= @msrecord.actual_sale %></td>
          <td><%= @msrecord.purchase_rate %></td>
          <td><%= @msrecord.sale_rate %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class='col-md-2'>
    <%= link_to edit_msrecord_path(@msrecord), class: "btn btn-warning btn-sm" do %>
      <i class="glyphicon glyphicon-pencil"></i> Edit
    <% end %>
    <%= link_to msrecord_path(@msrecord), class: "btn btn-danger btn-sm",
      method: :delete,
      data: { confirm: 'Are you sure?' } do %>
      <i class="glyphicon glyphicon-remove"></i> Delete
    <% end %>
  </div>
  <div>
    <%= link_to msrecords_path, class: "btn btn-info btn-sm" do %>
      <i class="glyphicon glyphicon-arrow-left"></i> Back
    <% end %>
  </div>
</div>